sonar.projectKey=python-game
sonar.projectName=Python Game
sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
sonar.python.version=3
sonar.tests=tests
sonar.exclusions=**/venv/**,**/__pycache__/**,**/*.pyc
