

image:
  repository: jeevan725/pygame
  tag: "v1.0.0"           # Pin version for stability
  pullPolicy: IfNotPresent

service:
  type: NodePort          # Can change to ClusterIP / LoadBalancer later
  port: 5000              # Flask app listens on 5000
  nodePort: 30080         # Only used if type=NodePort

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
    ephemeral-storage: "500Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
    ephemeral-storage: "1Gi"

