replicaCount: 1

image:
  repository: jeevan725/pygame
  tag: v182
  pullPolicy: Always

service:
  type: ClusterIP
  port: 5000

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
    ephemeral-storage: "500Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
    ephemeral-storage: "1Gi"

