apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pygame.fullname" . }}
  labels:
    app: {{ include "pygame.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pygame.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "pygame.name" . }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
              ephemeral-storage: {{ .Values.resources.requests["ephemeral-storage"] }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
              ephemeral-storage: {{ .Values.resources.limits["ephemeral-storage"] }}
          volumeMounts:
            - name: pygame-storage
              mountPath: /data
      volumes:
        - name: pygame-storage
          emptyDir: {}
