apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pygame.fullname" . }}
  labels:
    app: {{ include "pygame.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pygame.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "pygame.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
          # No volumeMounts over /app — templates baked into the image will be visible
